
import { ExceptionWord, MCQQuestion, ClassificationWord } from './types';

export const EXCEPTIONS: ExceptionWord[] = [
  { word: "Naked", ipa: "/ˈneɪkɪd/", meaning: "Trần trụi, khỏa thân", note: "with the naked eye (bằng mắt thường)" },
  { word: "Wicked", ipa: "/ˈwɪkɪd/", meaning: "Độc ác, tinh quái", note: "a wicked witch" },
  { word: "Beloved", ipa: "/bɪˈlʌvɪd/", meaning: "Yêu dấu", note: "my beloved country" },
  { word: "Sacred", ipa: "/ˈseɪkrɪd/", meaning: "Thần thánh, thiêng liêng", note: "a sacred animal" },
  { word: "Hatred", ipa: "/ˈheɪtrɪd/", meaning: "Lòng căm thù", note: "(Danh từ)" },
  { word: "Wretched", ipa: "/ˈretʃɪd/", meaning: "Khốn khổ, bần cùng", note: "a wretched life" },
  { word: "Rugged", ipa: "/ˈrʌɡɪd/", meaning: "Gồ ghề, lởm chởm", note: "rugged terrain" },
  { word: "Ragged", ipa: "/ˈræɡɪd/", meaning: "Rách rưới, tả tơi", note: "a ragged coat" },
  { word: "Dogged", ipa: "/ˈdɒɡɪd/", meaning: "Kiên cường, lì lợm", note: "dogged determination" },
  { word: "Learned", ipa: "/ˈlɜːrnɪd/", meaning: "Có học thức, uyên bác", note: "Chỉ dùng khi là Tính từ (a learned man)" },
  { word: "Aged", ipa: "/ˈeɪdʒɪd/", meaning: "Rất già, lão", note: "Chỉ dùng khi là Tính từ (an aged lady)" },
  { word: "Blessed", ipa: "/ˈblesɪd/", meaning: "May mắn, thiêng liêng", note: "Chỉ dùng khi là Tính từ (blessed innocence)" },
  { word: "Crooked", ipa: "/ˈkrʊkɪd/", meaning: "Cong, xoắn, không thật thà", note: "a crooked mirror" },
  { word: "Crabbed", ipa: "/ˈkræbɪd/", meaning: "Khó tính, chữ nhỏ khó đọc", note: "crabbed handwriting" },
  { word: "Cursed", ipa: "/ˈkɜːrsɪd/", meaning: "Đáng nguyền rủa", note: "Chỉ dùng khi là Tính từ" }
];

const rawMCQAnswers1 = "DBCADDBBCCADDAACCA DC BCCDAAABBBBDDDDB ABD BAAADABDDD".split(/\s+/).join("").split("");
const rawMCQAnswers2 = "BBACABAAADAAA AA BB A A C D B A A A B B B A A A A A A A D A A A A A A A A A".split(/\s+/).join("").split("");

const getIndex = (char: string) => {
    if (char === 'A') return 0;
    if (char === 'B') return 1;
    if (char === 'C') return 2;
    if (char === 'D') return 3;
    return 0;
};

// Simplified parser for the provided MCQ text to avoid humongous hardcoded arrays
export const MCQ_DATA_BASIC_RAW = [
    ["arrived", "believed", "received", "hoped"],
    ["opened", "knocked", "played", "occurred"],
    ["rubbed", "tugged", "stopped", "filled"],
    ["dimmed", "laughed", "passed", "worked"],
    ["decided", "waited", "handed", "designed"],
    ["packed", "punched", "pushed", "caused"],
    ["tested", "clapped", "planted", "demanded"],
    ["faxed", "happened", "fixed", "washed"],
    ["measured", "pleased", "distinguished", "managed"],
    ["united", "provided", "shouted", "looked"],
    ["formed", "started", "persuaded", "decided"],
    ["kissed", "helped", "forced", "raised"],
    ["warned", "climbed", "lived", "looked"],
    ["needed", "booked", "stopped", "washed"],
    ["invited", "attended", "celebrated", "displayed"],
    ["removed", "washed", "hoped", "missed"],
    ["looked", "laughed", "moved", "stepped"],
    ["wanted", "parked", "stopped", "watched"],
    ["believed", "prepared", "involved", "liked"],
    ["lifted", "lasted", "happened", "decided"],
    ["collected", "changed", "formed", "viewed"],
    ["walked", "entertained", "reached", "looked"],
    ["watched", "stopped", "pushed", "improved"],
    ["admired", "looked", "missed", "hoped"],
    ["attended", "appeared", "agreed", "played"],
    ["passed", "realized", "touched", "wished"],
    ["forced", "caused", "policed", "faxed"],
    ["widened", "editor", "acted", "printed"],
    ["signed", "profited", "became", "walked"],
    ["coughed", "weighed", "laughed", "matched"],
    ["walked", "hundred", "fixed", "danced"],
    ["studied", "raised", "played", "based"],
    ["boiled", "filled", "swallowed", "finished"],
    ["covered", "installed", "described", "decorated"],
    ["claimed", "warned", "occurred", "existed"],
    ["carried", "looked", "managed", "opened"],
    ["pleased", "smoked", "stopped", "missed"],
    ["agreed", "succeeded", "smiled", "loved"],
    ["allowed", "dressed", "flashed", "mixed"],
    ["switched", "stayed", "shared", "listened"],
    ["knocked", "naked", "needed", "kneaded"],
    ["called", "passed", "talked", "washed"],
    ["landed", "planted", "needed", "worked"],
    ["explained", "disappointed", "prepared", "interviewed"],
    ["questioned", "tried", "reused", "mixed"],
    ["followed", "enjoyed", "liked", "arrived"],
    ["decided", "behaved", "started", "visited"],
    ["rained", "played", "learned (v)", "walked"],
    ["sacrificed", "finished", "fixed", "seized"],
    ["cooked", "clicked", "booked", "naked"]
];

export const MCQ_QUESTIONS: MCQQuestion[] = [
    ...MCQ_DATA_BASIC_RAW.map((options, i) => ({
        id: i + 1,
        options,
        correctIndex: getIndex(rawMCQAnswers1[i]),
        level: 'Basic' as const
    })),
    // Advanced start from 51
    ...[
        ["learned (adj)", "watched", "wretched (adj)", "sacred (adj)"],
        ["beloved (adj)", "helped", "naked (adj)", "wicked (adj)"],
        ["used (v)", "crooked (adj)", "aged (adj)", "dogged (adj)"],
        ["crabbed (adj)", "ragged (adj)", "played", "learned (adj)"],
        ["cursed (adj)", "cursed (v)", "stopped", "washed"],
        ["blessed (v)", "blessed (adj)", "kissed", "dressed"],
        ["rugged (adj)", "hugged (v)", "dragged", "plugged"],
        ["hatred (n)", "liked", "washed", "hoped"],
        ["sacred (adj)", "scared (v)", "looked", "pushed"],
        ["deserved", "supposed", "proposed", "increased"],
        ["naked", "cooked", "booked", "walked"],
        ["beloved", "loved", "moved", "proved"],
        ["learned (adj)", "earned", "turned", "burned"],
        ["wretched", "stretched", "reached", "touched"],
        ["ragged", "managed", "damaged", "encouraged"],
        ["confused", "faced", "cried", "defined"],
        ["wicked", "kicked", "picked", "ticked"],
        ["aged (adj)", "caged", "managed", "damaged"],
        ["dogged", "hugged", "mugged", "logged"],
        ["crooked", "hooked", "cooked", "looked"],
        ["laughed", "photographed", "weighed", "coughed"],
        ["breathed", "teeth (v)", "bathed", "pushed"],
        ["advised", "practiced", "raised", "devised"],
        ["increased", "pleased", "erased", "confused"],
        ["used (to)", "used (v)", "closed", "raised"],
        ["replaced", "amazed", "dozed", "memorized"],
        ["naked", "worked", "asked", "liked"],
        ["impressed", "blessed (adj)", "depressed", "obsessed"],
        ["rugged", "drugged", "shrugged", "mugged"],
        ["hatred", "stopped", "cooked", "laughed"],
        ["markedly", "marked", "packed", "checked"],
        ["allegedly", "changed", "played", "lived"],
        ["deservedly", "served", "swerved", "carved"],
        ["supposedly", "closed", "raised", "posed"],
        ["fixedly", "fixed", "mixed", "boxed"],
        ["learned (adj)", "arrived", "lived", "stayed"],
        ["wretched", "washed", "watched", "stopped"],
        ["beloved", "helped", "missed", "fixed"],
        ["sacred", "played", "planned", "seemed"],
        ["crooked", "stopped", "looked", "booked"],
        ["ragged", "rained", "followed", "happened"],
        ["dogged", "decided", "wanted", "stopped"],
        ["aged (adj)", "played", "stayed", "enjoyed"],
        ["blessed (adj)", "stressed", "dressed", "pressed"],
        ["crabbed", "grabbed", "stabbed", "robbed"],
        ["cursed (adj)", "nursed", "dispersed", "reversed"],
        ["hatred", "moved", "lived", "arrived"],
        ["naked", "packed", "backed", "lacked"],
        ["wicked", "picked", "licked", "ticked"],
        ["rugged", "hugged", "bugged", "tugged"]
    ].map((options, i) => ({
        id: i + 51,
        options,
        correctIndex: getIndex(rawMCQAnswers2[i]),
        level: 'Advanced' as const
    }))
];

export const CLASSIFICATION_WORDS: ClassificationWord[] = [
    { id: 1, word: "added", category: "/ɪd/" },
    { id: 2, word: "washed", category: "/t/" },
    { id: 3, word: "loved", category: "/d/" },
    { id: 4, word: "naked (adj)", category: "/ɪd/" },
    { id: 5, word: "cooked", category: "/t/" },
    { id: 6, word: "played", category: "/d/" },
    { id: 7, word: "started", category: "/ɪd/" },
    { id: 8, word: "wicked (adj)", category: "/ɪd/" },
    { id: 9, word: "missed", category: "/t/" },
    { id: 10, word: "rained", category: "/d/" },
    { id: 11, word: "ended", category: "/ɪd/" },
    { id: 12, word: "kissed", category: "/t/" },
    { id: 13, word: "cleaned", category: "/d/" },
    { id: 14, word: "sacred (adj)", category: "/ɪd/" },
    { id: 15, word: "watched", category: "/t/" },
    { id: 16, word: "stayed", category: "/d/" },
    { id: 17, word: "wanted", category: "/ɪd/" },
    { id: 18, word: "learned (adj)", category: "/ɪd/" },
    { id: 19, word: "laughed", category: "/t/" },
    { id: 20, word: "arrived", category: "/d/" },
    { id: 21, word: "decided", category: "/ɪd/" },
    { id: 22, word: "stopped", category: "/t/" },
    { id: 23, word: "moved", category: "/d/" },
    { id: 24, word: "beloved (adj)", category: "/ɪd/" },
    { id: 25, word: "looked", category: "/t/" },
    { id: 26, word: "lived", category: "/d/" },
    { id: 27, word: "visited", category: "/ɪd/" },
    { id: 28, word: "ragged (adj)", category: "/ɪd/" },
    { id: 29, word: "danced", category: "/t/" },
    { id: 30, word: "used", category: "/d/" },
    { id: 31, word: "needed", category: "/ɪd/" },
    { id: 32, word: "walked", category: "/t/" },
    { id: 33, word: "changed", category: "/d/" },
    { id: 34, word: "dogged (adj)", category: "/ɪd/" },
    { id: 35, word: "helped", category: "/t/" },
    { id: 36, word: "followed", category: "/d/" },
    { id: 37, word: "invited", category: "/ɪd/" },
    { id: 38, word: "wretched (adj)", category: "/ɪd/" },
    { id: 39, word: "worked", category: "/t/" },
    { id: 40, word: "opened", category: "/d/" },
    { id: 41, word: "pointed", category: "/ɪd/" },
    { id: 42, word: "hoped", category: "/t/" },
    { id: 43, word: "called", category: "/d/" },
    { id: 44, word: "rugged (adj)", category: "/ɪd/" },
    { id: 45, word: "relaxed", category: "/t/" },
    { id: 46, word: "listened", category: "/d/" },
    { id: 47, word: "waited", category: "/ɪd/" },
    { id: 48, word: "aged (adj)", category: "/ɪd/" },
    { id: 49, word: "fixed", category: "/t/" },
    { id: 50, word: "cried", category: "/d/" },
    { id: 51, word: "intended", category: "/ɪd/" },
    { id: 52, word: "brushed", category: "/t/" },
    { id: 53, word: "seemed", category: "/d/" },
    { id: 54, word: "crooked (adj)", category: "/ɪd/" },
    { id: 55, word: "promised", category: "/t/" },
    { id: 56, word: "allowed", category: "/d/" },
    { id: 57, word: "planted", category: "/ɪd/" },
    { id: 58, word: "blessed (adj)", category: "/ɪd/" },
    { id: 59, word: "passed", category: "/t/" },
    { id: 60, word: "burned", category: "/d/" },
    { id: 61, word: "demanded", category: "/ɪd/" },
    { id: 62, word: "checked", category: "/t/" },
    { id: 63, word: "agreed", category: "/d/" },
    { id: 64, word: "crabbed (adj)", category: "/ɪd/" },
    { id: 65, word: "mixed", category: "/t/" },
    { id: 66, word: "believed", category: "/d/" },
    { id: 67, word: "included", category: "/ɪd/" },
    { id: 68, word: "cursed (adj)", category: "/ɪd/" },
    { id: 69, word: "dressed", category: "/t/" },
    { id: 70, word: "enjoyed", category: "/d/" },
    { id: 71, word: "completed", category: "/ɪd/" },
    { id: 72, word: "typed", category: "/t/" },
    { id: 73, word: "worried", category: "/d/" },
    { id: 74, word: "hatred (n)", category: "/ɪd/" },
    { id: 75, word: "pushed", category: "/t/" },
    { id: 76, word: "tried", category: "/d/" },
    { id: 77, word: "attended", category: "/ɪd/" },
    { id: 78, word: "markedly (adv)", category: "/ɪd/" },
    { id: 79, word: "touched", category: "/t/" },
    { id: 80, word: "died", category: "/d/" },
    { id: 81, word: "polluted", category: "/ɪd/" },
    { id: 82, word: "coughed", category: "/t/" },
    { id: 83, word: "happened", category: "/d/" },
    { id: 84, word: "learned (v)", category: "/d/" },
    { id: 85, word: "jumped", category: "/t/" },
    { id: 86, word: "snowed", category: "/d/" },
    { id: 87, word: "fascinated", category: "/ɪd/" },
    { id: 88, word: "blessed (v)", category: "/t/" },
    { id: 89, word: "liked", category: "/t/" },
    { id: 90, word: "turned", category: "/d/" },
    { id: 91, word: "painted", category: "/ɪd/" },
    { id: 92, word: "developed", category: "/t/" },
    { id: 93, word: "explained", category: "/d/" },
    { id: 94, word: "tasted", category: "/ɪd/" },
    { id: 95, word: "introduced", category: "/t/" },
    { id: 96, word: "answered", category: "/d/" },
    { id: 97, word: "divided", category: "/ɪd/" },
    { id: 98, word: "faxed", category: "/t/" },
    { id: 99, word: "carried", category: "/d/" },
    { id: 100, word: "recommended", category: "/ɪd/" }
];
